version: 2

plan:
  project-key: QA
  key: PLAYWRIGHT
  name: Playwright Tests

stages:
  - Stage 1:
      jobs:
        - Run Playwright Tests

jobs:
  - job: Run Playwright Tests
    tasks:
      - checkout:
          force-clean-build: true
      - script:
          interpreter: BINSH_OR_CMD
          scripts:
            - echo "Running Playwright tests"
            - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
      - script:
          description: Generate Allure Report
          scripts:
            - mvn allure:report
    artifacts:
      - name: Allure Report
        pattern: target/site/allure-maven-plugin/**