name: Run Playwright Tests with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run tests in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/target:/app/target \
            playwright-tests test

      - name: Install Allure CLI (skip if already installed)
        run: |
          if ! command -v allure &> /dev/null; then
            echo "🔧 Installing Allure CLI..."
            curl -Lo allure.zip https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip
            unzip -o allure.zip -d /opt/allure
            sudo ln -sf /opt/allure/allure-2.24.0/bin/allure /usr/local/bin/allure
            rm allure.zip
          else
            echo "✅ Allure CLI already installed"
          fi

      - name: Generate Allure report
        run: ./generate-allure-report.sh

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download Allure report artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

